// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutMediaOverlay from '@/components/sections/about/AboutMediaOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutMediaOverlay
          tag="About Us"
          title="Your Trusted Local Contractor"
          description="Led by Isidro Palafox, Palafox Construction is a hands-on local business built on the pillars of honesty and quality craftsmanship. We take pride in doing the job right the first time, ensuring every homeowner feels respected and every project exceeds expectations."
          imageSrc="http://img.b2bpic.net/free-photo/portrait-male-builder-construction-site_169016-15095.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
