// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Get Started"
          text="Ready to improve your property? Contact Isidro Palafox today for a free estimate. 805-610-6625 | palafoxconstruction@gmail.com | License #957719"
          primaryButton={{
            text: "Call Now",
            href: "tel:8056106625",
          }}
          secondaryButton={{
            text: "Email Us",
            href: "mailto:palafoxconstruction@gmail.com",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
