// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "gallery" section.

import React from 'react';
import MetricsMediaCards from '@/components/sections/metrics/MetricsMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function GallerySection(): React.JSX.Element {
  return (
    <div id="gallery" data-section="gallery">
        <SectionErrorBoundary name="gallery">
              <MetricsMediaCards
        tag="Projects"
        title="Our Work in Atascadero"
        description="A glimpse into the quality projects we have completed for our community."
        metrics={[
            {
              title: "Outdoor Decks",
              description: "Custom decks built for comfort.",
              value: "100+",
              imageSrc: "http://img.b2bpic.net/free-photo/empty-chair-park_1339-6076.jpg",
            },
            {
              title: "Fencing",
              description: "Sturdy privacy fencing.",
              value: "200+",
              imageSrc: "http://img.b2bpic.net/free-photo/closeup-shot-stone-pavement-made-blocks-grass-winter_181624-42753.jpg",
            },
            {
              title: "Remodels",
              description: "Interior renovations completed.",
              value: "50+",
              imageSrc: "http://img.b2bpic.net/free-photo/handsome-young-man-opening-fridge_23-2148351743.jpg",
            },
          ]}
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
