/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import HeroBackgroundSlot from "@/components/ui/HeroBackgroundSlot";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import AvatarGroup from "@/components/ui/AvatarGroup";

const avatarsSrc = [
  "https://picsum.photos/seed/avatar1/100/100",
  "https://picsum.photos/seed/avatar2/100/100",
  "https://picsum.photos/seed/avatar3/100/100"
];
const primaryButton = {
  text: "Call Now",
  href: "tel:8056106625"
};
const secondaryButton = {
  text: "Get an Estimate",
  href: "#contact"
};
const names = [
  "Atascadero Homes",
  "California Quality",
  "Palafox Craft",
  "Central Coast"
];

type HeroCenteredLogosProps = {
  avatarsSrc: string[];
  avatarText: string;
  title: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
  names: string[];
  hideMedia?: boolean;
  textAnimation: "slide-up" | "fade-blur" | "fade";
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const HeroInline = () => {
  return (
    <section aria-label="Hero section" className="relative h-svh flex flex-col mb-20">
      <HeroBackgroundSlot />
      {!undefined && (
        <div className="absolute inset-0 z-0">
          <ImageOrVideo imageSrc={"http://img.b2bpic.net/free-photo/side-view-couple-with-paint-rollers-ladder_23-2147782356.jpg"} className="size-full object-cover" />
          <div className="absolute inset-0 bg-background/80" />
        </div>
      )}

      <div className="relative z-10 flex-1 flex items-center justify-center">
        <div className="flex flex-col items-center gap-3 pt-8 w-content-width mx-auto text-center">
          <AvatarGroup avatarsSrc={avatarsSrc} label={"Trusted by 500+ homeowners in Atascadero & surrounding areas"} size="lg" />


          <TextAnimation
            text={"PALAFOX CONSTRUCTION"}
            variant={"slide-up"}
            gradientText={true}
            tag="h1"
            className="md:max-w-8/10 text-6xl md:text-8xl leading-[1.1] font-black text-center uppercase tracking-tight"
          />

          <TextAnimation
            text={"WE ARE YOUR HOME IMPROVEMENT EXPERTS - LIC# 957719"}
            variant={"slide-up"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-xl md:text-2xl leading-snug text-balance font-extrabold text-primary-cta"
          />

          <a href="tel:8056106625" className="text-4xl md:text-6xl font-black text-foreground hover:underline my-2 tracking-wider">
            805·610·6625
          </a>

          <p className="text-base md:text-lg font-bold text-foreground/80 uppercase tracking-widest">
            PALAFOXCONSTRUCTION@GMAIL.COM • ISIDRO PALAFOX • ATASCADERO, CA 93422
          </p>

          <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
            <Button text={primaryButton.text} href={primaryButton.href} variant="primary" />
            <Button text={secondaryButton.text} href={secondaryButton.href} variant="secondary" animationDelay={0.1} />
          </div>
        </div>
      </div>

      <div className="relative z-10 w-content-width mx-auto pb-8 overflow-hidden mask-fade-x">
        <div className="flex w-max animate-marquee-horizontal" style={{ animationDuration: "30s" }}>
          {[...names, ...names, ...names, ...names].map((name, index) => (
            <div key={index} className="shrink-0 mx-3 px-4 py-2 card rounded">
              <span className="text-xl font-semibold whitespace-nowrap text-foreground/75">{name}</span>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default function HeroSection() {
  return (
    <div data-webild-section="hero" data-section="hero" id="hero">
      <HeroInline />
    </div>
  );
}
