// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroCenteredLogos from '@/components/sections/hero/HeroCenteredLogos';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroCenteredLogos
        avatarsSrc={[
            "https://picsum.photos/seed/avatar1/100/100",
            "https://picsum.photos/seed/avatar2/100/100",
            "https://picsum.photos/seed/avatar3/100/100",
          ]}
        avatarText="Trusted by 500+ homeowners in Atascadero & surrounding areas"
        title="We Are Your Home Improvement Experts"
        description="Quality work for Atascadero, California 93422, and surrounding areas. From residential repairs to light commercial projects, we treat every property like our own."
        primaryButton={{
            text: "Call Now",
            href: "tel:8056106625",
          }}
        secondaryButton={{
            text: "Get an Estimate",
            href: "#contact",
          }}
        names={["Atascadero Homes","California Quality","Palafox Craft","Central Coast"]}
        imageSrc="http://img.b2bpic.net/free-photo/side-view-couple-with-paint-rollers-ladder_23-2147782356.jpg"
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
