// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesRevealCardsBento
          tag="Our Services"
          title="Comprehensive Improvement Projects"
          description="No job is too big or too small. We specialize in residential and light commercial work."
          items={[
            {
              title: "Fencing",
              description: "Custom wood, chain-link, and privacy fencing.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/swimming-ocean-vacation-summer-chair_1203-4051.jpg",
            },
            {
              title: "Landscaping",
              description: "Full-service landscaping and yard transformations.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/photo-ground-texture-pattern_58702-11928.jpg",
            },
            {
              title: "Remodeling",
              description: "Kitchen and bathroom remodeling projects.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/side-view-front-door-with-pink-wall-plants_23-2149360589.jpg",
            },
            {
              title: "Concrete & Hardscaping",
              description: "Driveways, walkways, and patio hardscaping.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/man-pouring-drink-his-girlfriend-sitting-rooftop_23-2147891094.jpg",
            },
            {
              title: "Decks & Patios",
              description: "Building custom decks and outdoor living spaces.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-female-athlete-exercising-staircase-winter_23-2147905357.jpg",
            },
            {
              title: "Painting",
              description: "Professional interior and exterior painting services.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/service-worker-painting-car-auto-service_23-2149486992.jpg",
            },
            {
              title: "General Repairs",
              description: "Handyman services for your home improvement needs.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/minimalist-courtyard-pool-design_23-2151934177.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
